import type { NextPage } from 'next'
import Head from 'next/head'
import NavBar from "../components/NavBar"
import mainPage from './mainPage';
import { io } from "socket.io-client";
import styles from '../styles/Home.module.css'

// export const socket = io("http://localhost:3001");

const Home: NextPage = () => {
	//Connect to server
	// socket.on("connect", () => {
	// 	console.log("connection established ", socket.id);
	// 	sessionStorage.setItem("socket", socket);
	// });
	
	return (
		<div className={styles.container}>
			<Head>
				<title>Login Page</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className={styles.main}>
				<a href="https://api.intra.42.fr/oauth/authorize?client_id=95976106d24d16c4735c8b3f39334abfb699b1295edc3ecb1b149054e27373b4&redirect_uri=https%3A%2F%2Flocalhost%3A3000%2FmainPage&response_type=code">Try to connect</a>
				<NavBar />
			</main>

			<footer className={styles.footer}>
			</footer>
		</div>
	)
	
}

export default Home
