import type { NextPage } from 'next'
import Head from 'next/head'
import NavBar from "../components/NavBar"
import { io } from "socket.io-client";
import styles from '../styles/Home.module.css'
import ClientOAuth2 from 'client-oauth2';

// Create a socket to communicate with the backend
export const socket = io("http://localhost:3001");

// Create a new instance of the OAuth 2.0 client
// process.env permet de recuperer les variables d'environnement
export var auth42 = new ClientOAuth2({
	clientId: process.env.AUTH0_CLIENT_ID,
	clientSecret: process.env.AUTH0_CLIENT_SECRET,
	accessTokenUri: "https://api.intra.42.fr/oauth/token",
	authorizationUri: "https://api.intra.42.fr/oauth/authorize",
	redirectUri: "https://localhost:3000/mainPage",
})

export function getSocket() {
	return socket;
}

const Home: NextPage = () => {

	// Connect socket to the backend
	socket.on("connect", () => {
		console.log("connection established ", socket.id);
	});

	// Get the URL to which the user will be redirected for authorization
	var url:string = auth42.code.getUri();

	return (
		<div className={styles.container}>
			<Head>
				<title>Login Page</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="./public/favicon.ico" />
			</Head>
			<NavBar />
			<main className={styles.login}>
				<a href={url}>Try to connect</a>
			</main>
		</div>
	)
}

export default Home;
