
###################
# SOURCES : https://www.tomray.dev/nestjs-docker-compose-postgres
# BUILD FOR LOCAL DEVELOPMENT
###################

FROM        node:current-alpine As development

# Create app directory
WORKDIR     /usr/src/app

COPY 		--chown=node:node ./react/package*.json /usr/src/app/

RUN         apk update && \
            apk add openssl && \
            openssl req -x509 -newkey rsa:4096 -keyout /etc/ssl/private/.pong.key -out /etc/ssl/certs/pong.csr -days 365 -nodes -subj "/CN=frontend" && \
            npm install -g npm@latest


# Install app dependencies using the `npm ci` command instead of `npm install`
RUN         npm install

# Bundle app source
COPY 		./react /usr/src/app
COPY 		./scripts/dev_entrypoint.sh /home/node/