
#https://dev.to/erezhod/setting-up-a-nestjs-project-with-docker-for-back-end-development-30lg

version: '3.8'
services:
  front_dev:
    depends_on:
      - back_dev
    container_name: front_dev
    build:
      context: ./frontend
      target: development
      dockerfile: ./Dockerfile
    command: npm start
    # links:
    #   - back_dev
    volumes:
      - ./frontend/react/src:/usr/src/app/src
    restart: unless-stopped
    env_file:
    - ./frontend/frontend.env
    ports:
       - 3000:3000
    
  back_dev:
    depends_on:
    - postgres
    container_name: nestjs_api_dev
    image: nestjs-api-dev:1.0.0
    build:
      context: ./backend
      target: development
      dockerfile: ./Dockerfile
    volumes:
      - ./backend/data_to_container/pong/:/usr/src/app/
    command: sh /home/node/dev_entrypoint.sh
    restart: unless-stopped
    env_file:
    - ./backend/backend.env
    ports:
      - 3010:3010
      - 3011:3011

  postgres:
    container_name: postgres_dev
    image: postgres:latest
    volumes:
      - pgVolume:/var/lib/postgresql/data
    restart: always
    env_file:
    - ./postgres/postgres.env
    ports:
      - "3020:3020"

  pg_admin:
    depends_on:
    - postgres
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    env_file:
    - pg_admin/pg_admin.env
    ports:
      - "3030:80"

volumes:
  pgVolume: