version: '3'
services:
  frontend:
    build: ./frontend
    volumes:
      - /app/nodes_modules
      - ./frontend:/app
    ports:
      -80:3000
      
  #   depends_on:
  #     - backend
    
  # backend:
  #   build: ./backend
  #   ports:
  #     -80:8080
  #   depends_on:
  #     - db