
#https://dev.to/erezhod/setting-up-a-nestjs-project-with-docker-for-back-end-development-30lg

version: '3.8'
services:
  frontend:
    depends_on:
      - backend
    container_name: frontend
    build:
      context: ./frontend
      target: development
      dockerfile: ./Dockerfile
    command: sh /home/node/scripts/dev_entrypoint.sh
    volumes:
      - ./frontend/react:/usr/src/app/
      - ./frontend/scripts/:/home/node/scripts/
    restart: unless-stopped
    env_file:
    - env/.env
    - env/urls.env
    - env/api.env
    - env/frontend.env
    ports:
       - 3000:3000
    
  backend:
    depends_on:
    - postgres
    container_name: backend
    image: nestjs-api-dev:1.0.0
    build:
      context: ./backend
      target: development
      dockerfile: ./Dockerfile
    volumes:
      - ./backend/data_to_container/pong/:/usr/src/app/
    command: sh /home/node/dev_entrypoint.sh
    restart: unless-stopped
    env_file:
    - env/.env
    - env/.secret.env
    - env/urls.env
    - env/api.env
    - env/backend.env
    - env/postgres.env
    ports:
      - 3010:3010
      - 3011:3011

  postgres:
    container_name: postgres
    image: postgres:latest
    volumes:
      - pgVolume:/var/lib/postgresql/data
    restart: always
    env_file:
    - env/.env
    - env/postgres.env
    ports:
      - "3020:3020"

  pg_admin:
    depends_on:
    - postgres
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    env_file:
    - env/.env
    - env/pg_admin.env
    ports:
      - "3030:80"

volumes:
  pgVolume: