
#https://dev.to/erezhod/setting-up-a-nestjs-project-with-docker-for-back-end-development-30lg
# https://www.grottedubarbu.fr/docker-nginx-reverse-proxy/

version: '3.8'
services:
  reverse_proxy:
    depends_on:
      - frontend
    networks:
      - pong_prod_frontend
      - pong_prod_backend
    build:
      context: ./reverse_proxy
      dockerfile: ./Dockerfile
    container_name: reverse_proxy
    command: /bin/sh /home/nginx/entrypoint.sh
    restart: unless-stopped
    ports:
       - 4443:443
    env_file:
    - .env

  frontend:
    depends_on:
      - backend
    container_name: frontend
    build:
      context: ./frontend
      target: production
      dockerfile: ./Dockerfile
    command: /bin/sh /home/nginx/prod_entrypoint.sh
    networks:
      - pong_prod_frontend
    restart: unless-stopped
    env_file:
    - .env
    
  backend:
    depends_on:
    - postgres
    container_name: backend
    build:
      context: ./backend
      target: production
      dockerfile: ./Dockerfile
    volumes:
      - PPVolume:/usr/src/app/uploads/
    networks:
      - pong_prod_database
      - pong_prod_backend
    command: /bin/sh /home/node/prod_entrypoint.sh
    restart: unless-stopped
    env_file:
    - .env

  postgres:
    container_name: postgres
    image: postgres:latest
    volumes:
      - pgVolume:/var/lib/postgresql/data
    networks:
      - pong_prod_database
    restart: always
    env_file:
    - .env

volumes:
  pgVolume:
  PPVolume:

networks:
  pong_prod_frontend:
  pong_prod_backend:
  pong_prod_database: