
#https://dev.to/erezhod/setting-up-a-nestjs-project-with-docker-for-back-end-development-30lg
# https://www.grottedubarbu.fr/docker-nginx-reverse-proxy/

version: '3.8'
services:
  reverse-proxy:
    depends_on:
      - backend
      - frontend
      - postgres
    container_name: reverse_proxy
    image: nginx
    volumes:
      - ./reverse_proxy/nginx.temp:/etc/nginx/nginx.temp
      - ./reverse_proxy/ssl/:/etc/ssl/pong/
    command: /bin/sh -c "envsubst '$${REACT_APP_RP_BACK_URL} $${REACT_APP_RP_FRONT_URL} '< /etc/nginx/nginx.temp > /etc/nginx/nginx.conf && exec nginx -g 'daemon off;'"
    restart: unless-stopped
    env_file:
    - env/.env
    - env/urls.env
    ports:
       - 4443:443

  frontend:
    depends_on:
      - backend
    container_name: frontend
    build:
      context: ./frontend
      target: development
      dockerfile: ./Dockerfile
    command: sh /home/node/scripts/dev_entrypoint.sh
    volumes:
      - ./frontend/react:/usr/src/app/
      - ./frontend/scripts/:/home/node/scripts/
    restart: unless-stopped
    env_file:
    - env/.env
    - env/urls.env
    - env/pong.env
    - env/frontend.env
    ports:
       - 3000:3000
    
  backend:
    depends_on:
    - postgres
    container_name: backend
    image: nestjs-api-dev:1.0.0
    build:
      context: ./backend
      target: development
      dockerfile: ./Dockerfile
    volumes:
      - ./backend/data_to_container/pong/:/usr/src/app/
    command: sh /home/node/dev_entrypoint.sh
    restart: unless-stopped
    env_file:
    - env/.env
    - env/.secret.env
    - env/urls.env
    - env/backend.env
    - env/pong.env
    - env/postgres.env
    ports:
      - 3010:3010
      - 3011:3011

  postgres:
    container_name: postgres
    image: postgres:latest
    volumes:
      - pgVolume:/var/lib/postgresql/data
    restart: always
    env_file:
    - env/.env
    - env/postgres.env
    ports:
      - "3020:3020"

  pg_admin:
    depends_on:
    - postgres
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    env_file:
    - env/.env
    - env/pg_admin.env
    ports:
      - "3030:80"

volumes:
  pgVolume: